version: "3.8"

services:
  postgres:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_DB: EveSeminovos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
