version: "3.8"

services:
  postgres:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    environment:
      POSTGRES_DB: EveSeminovos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
