version: "3.8"

services:
  postgres:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_DB: EveSeminovos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: EveSeminovos
      JWT_SECRET_KEY: 1ee378cc-accc-4904-9f4e-3f729ae3a3a3
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    command: ["./wait-postgres.sh", "postgres", "5432", "python", "run.py"]

  frontend:
    build:
      context: ./frontend/eve-seminovos
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  eve-seminovos:
    driver: bridge
