
CREATE TABLE IF NOT EXISTS carros (
    id INT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    marca VARCHAR(255) NOT NULL,
    ano INT NOT NULL,
    preco DECIMAL(18,2) NOT NULL,
    img VARCHAR(255) NOT NULL
);

COPY carros (id, nome, marca, ano, preco, img)
FROM '/var/opt/data/carros.csv' DELIMITER ';' CSV HEADER;


CREATE TABLE IF NOT EXISTS usuarios (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    admin INT NOT NULL
);

COPY usuarios (usuario, senha, admin)
FROM '/var/opt/data/usuarios.csv' DELIMITER ';' CSV HEADER;